services:
  mongodb:
    container_name: mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_DB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_COLLECTION: ${COUNTER_COLLECTION}
      MONGO_USER_COLLECTION: ${USER_COLLECTION}
    ports:
      - 27017:27017
    volumes: 
      - mongo-data:/data/db
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  node-app:
    container_name: node-app
    platform: linux/amd64
    build: .
    ports:
      - ${NODE_APP_PORT}:${NODE_APP_PORT}
    depends_on:
      - mongodb
    volumes:
      - .:/src
    links:
      - "mongodb"
      
volumes:
  mongo-data:
